# Generated by Django 5.2.4 on 2025-07-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('hiring_timeline', models.CharField(help_text="e.g., 'August 2025', 'Q3 2025'", max_length=255)),
                ('drive_date', models.DateField(help_text='Primary date for ordering drives')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_process_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreparationTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('course', 'Course'), ('problem', 'Problem Set')], max_length=50)),
                ('associated_topics', models.ManyToManyField(related_name='resources', to='core.preparationtopic')),
            ],
        ),
        migrations.AddField(
            model_name='preparationtopic',
            name='associated_skills',
            field=models.ManyToManyField(related_name='prep_topics', to='core.skill'),
        ),
    ]
