# Generated by Django 5.2.4 on 2025-07-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g., Software Engineer, Data Analyst', max_length=100)),
                ('question_text', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50)),
                ('question_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('system_design', 'System Design'), ('aptitude', 'Aptitude')], default='technical', max_length=50)),
                ('expected_answer_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for basic assessment')),
                ('sample_answer', models.TextField(blank=True, help_text='A model answer for reference')),
                ('company', models.ForeignKey(blank=True, help_text='Optional: company this question is specific to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.companydrive')),
            ],
        ),
    ]
