# Generated by Django 5.2.4 on 2025-07-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mockinterviewquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockinterviewquestion',
            name='company',
        ),
        migrations.RemoveField(
            model_name='preparationtopic',
            name='associated_skills',
        ),
        migrations.DeleteModel(
            name='LearningResource',
        ),
        migrations.DeleteModel(
            name='MockInterviewQuestion',
        ),
        migrations.DeleteModel(
            name='PreparationTopic',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
